name: Check Server Status

on:
  schedule:
    - cron: "0 */3 * * *" # This cron schedule runs the job every 3 hours
  workflow_dispatch:

jobs:
  check-server-status:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_status.outputs.status }}

    steps:
      - name: Download previous status file or create a new one
        uses: actions/download-artifact@v4
        with:
          name: previous-status
          path: .
        continue-on-error: true

      - name: Ensure previous status file exists
        run: |
          if [ ! -f previous_status.txt ]; then
            echo "unknown" > previous_status.txt
          fi

      - name: Send request to the application
        id: check_status
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null ${{ secrets.APP_URL }})
          echo "HTTP response code: $response"
          if [ "$response" -eq 200 ]; then
            echo "Server is up and running"
            echo "status=up" >> $GITHUB_ENV
            echo "up" > status.txt
          else
            echo "Server is down"
            echo "status=down" >> $GITHUB_ENV
            echo "down" > status.txt
          fi

      - name: Set status output
        id: set_status
        run: |
          echo "status=$(cat status.txt)" >> $GITHUB_ENV
          echo "status=$(cat status.txt)" >> $GITHUB_OUTPUT

      - name: Upload new status as artifact
        uses: actions/upload-artifact@v4
        with:
          name: previous-status
          path: previous_status.txt
        if: always() # Ensure upload even if previous steps fail

  notify:
    needs: check-server-status
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download previous status file or create a new one
        uses: actions/download-artifact@v4
        with:
          name: previous-status
          path: .
        continue-on-error: true

      - name: Check previous status
        run: |
          if [ ! -f previous_status.txt ]; then
            echo "unknown" > previous_status.txt
          fi
          previous_status=$(cat previous_status.txt)
          echo "Previous status: $previous_status"
          echo "previous_status=$previous_status" >> $GITHUB_ENV

      - name: Debug environment variables
        run: |
          echo "Current status: ${{ needs.check-server-status.outputs.status }}"
          echo "Previous status: ${{ env.previous_status }}"

      - name: Update status file
        run: echo "${{ needs.check-server-status.outputs.status }}" > previous_status.txt

      - name: Upload updated status file
        uses: actions/upload-artifact@v4
        with:
          name: previous-status
          path: previous_status.txt
        if: always() # Ensure upload even if previous steps fail

      - name: Send Slack notification if server is down
        if: ${{ needs.check-server-status.outputs.status == 'down' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: ":red_circle: The server is currently down. Immediate attention is required.\n*Site*: <https://pfe-two.vercel.app|Visit Site>"
          SLACK_TITLE: "Server Status Alert - Down"
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITORING_WEBHOOK_URL }}

      - name: Send Slack notification if server is back up
        if: ${{ needs.check-server-status.outputs.status == 'up' && env.previous_status == 'down' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_MESSAGE: ":white_check_mark: The server is back up and running smoothly.\n*Site*: <https://pfe-two.vercel.app|Visit Site>"
          SLACK_TITLE: "Server Status Alert - Up"
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITORING_WEBHOOK_URL }}
