name: Check Server Status

on:
  schedule:
    - cron: "0 * * * *" # This cron schedule runs the job every hour
  workflow_dispatch:

jobs:
  check-server-status:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.set_status.outputs.status }}

    steps:
      - name: Send request to the application
        id: check_status
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null ${{ secrets.APP_URL }})
          echo "HTTP response code: $response"
          if [ "$response" -eq 200 ]; then
            echo "Server is up and running"
            echo "status=up" >> $GITHUB_ENV
            echo "up" > status.txt
          else
            echo "Server is down"
            echo "status=down" >> $GITHUB_ENV
            echo "down" > status.txt
          fi
      - name: Set status output
        id: set_status
        run: echo "::set-output name=status::$(cat status.txt)"

  notify:
    needs: check-server-status
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Check previous status
        id: check_previous_status
        run: |
          if [ -f previous_status.txt ]; then
            previous_status=$(cat previous_status.txt)
          else
            previous_status="unknown"
          fi
          echo "Previous status: $previous_status"
          echo "previous_status=$previous_status" >> $GITHUB_ENV

      - name: Update status file
        run: echo "${{ needs.check-server-status.outputs.status }}" > previous_status.txt

      - name: Debug environment variables
        run: |
          echo "Current status: ${{ needs.check-server-status.outputs.status }}"
          echo "Previous status: ${{ env.previous_status }}"

      - name: Send Slack notification if server is down
        if: ${{ needs.check-server-status.outputs.status == 'down' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: ":red_circle: The server is currently down. Immediate attention is required.\n[View Dashboard](https://pfe-two.vercel.app)"
          SLACK_TITLE: "Server Status Alert - Down"
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITORING_WEBHOOK_URL }}

      - name: Send Slack notification if server is back up
        if: ${{ needs.check-server-status.outputs.status == 'up' && env.previous_status == 'down' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_MESSAGE: ":white_check_mark: The server is back up and running smoothly.\n[View Dashboard](https://pfe-two.vercel.app)"
          SLACK_TITLE: "Server Status Alert - Up"
          MSG_MINIMAL: true
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITORING_WEBHOOK_URL }}
