name: Check Server Status

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  check-server-status:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.set_status.outputs.status }}
      artifact_name: ${{ steps.set_artifact_name.outputs.artifact_name }}

    steps:
      - name: Define unique artifact name
        id: set_artifact_name
        run: echo "::set-output name=artifact_name::previous-status-${{ github.run_number }}-${{ github.job }}"

      - name: Send request to the application
        id: check_status
        run: |
          response=$(curl --write-out '%{http_code}' --silent --output /dev/null ${{ secrets.APP_URL }})
          echo "HTTP response code: $response"
          if [ "$response" -eq 200 ]; then
            echo "Server is up and running"
            echo "status=up" >> $GITHUB_ENV
            echo "up" > status.txt
          else
            echo "Server is down or inaccessible"
            echo "status=down" >> $GITHUB_ENV
            echo "down" > status.txt
          echo "status=$(cat status.txt)" >> $GITHUB_OUTPUT

      - name: Upload status as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_artifact_name.outputs.artifact_name }}
          path: status.txt
        if: always() # Ensure upload even if previous steps fail

  notify:
    needs: check-server-status
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download previous status file
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.check-server-status.outputs.artifact_name }}
          path: .

      - name: Debug environment variables
        run: |
          echo "Current status: ${{ needs.check-server-status.outputs.status }}"
          echo "Artifact name used: ${{ needs.check-server-status.outputs.artifact_name }}"

      - name: Send Slack notification if server is down
        if: ${{ needs.check-server-status.outputs.status == 'down' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: danger
          SLACK_MESSAGE: ":red_circle: The server is currently down. Immediate attention is required.\n*Site*: <https://pfe-two.vercel.app|Visit Site>"
          SLACK_TITLE: "Server Status Alert - Down"
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITORING_WEBHOOK_URL }}

      - name: Send Slack notification if server is back up
        if: ${{ needs.check-server-status.outputs.status == 'up' }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: good
          SLACK_MESSAGE: ":white_check_mark: The server is back up and running smoothly.\n*Site*: <https://pfe-two.vercel.app|Visit Site>"
          SLACK_TITLE: "Server Status Alert - Up"
          SLACK_WEBHOOK: ${{ secrets.SLACK_MONITORING_WEBHOOK_URL }}
